services:
  card-api:
    container_name: card-api
    image: dario-service-card-api:latest
    build:
      context: ..
      dockerfile: Card/Dockerfile

    restart: unless-stopped

    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: http://0.0.0.0:${SERVICE_PORT}
      CardServices__ServicePort: "${SERVICE_PORT}"
      CardServices__ConnectionString: "${CARD_DB_CONNECTION_STRING}"
      CardServices__ConnectionStringQuery: "${CARD_DB_CONNECTION_STRING_QUERY}"
      CardServices__DatabaseProvider: "${CARD_DATABASE_PROVIDER}"
      CardServices__EncryptionKey: "${CARD_ENCRYPTION_KEY}"
      DB_CONNECTION_STRING: "${CARD_DB_CONNECTION_STRING}"
      DB_QUERY_CONNECTION_STRING: "${CARD_DB_CONNECTION_STRING_QUERY}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
      OTEL_EXPORTER_OTLP_PROTOCOL: "${OTEL_EXPORTER_OTLP_PROTOCOL:-grpc}"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=Dario.Service.Card.API,service.version=1.0.0,deployment.environment=Production"

    networks:
      - rayan

networks:
  rayan:
    external: true